#POO: PROGRAMACION ORIENTADA A OBJETOS
#OPP

#PERSONAS: CLASE
#ATRIBUTOS:
  #NOMBRE
  #APELLIDO
  #EDAD
  #DIRECCION
  #TELEFONO
  #CORREO ELECTRONICO
  
#PERSONA 1= PERSONA(123456, GABRIEL, PALOMINO, 20, 1987, GABRIEL523@GMAILCOM)

#PRODUCTO: CLASE
#ATRIBUTOS:
   #ID
   #PRECIOS
   #DESCRIPCION
   #CANTIDAD

#PRODUCTO1= PRODUCTO(1, 15, ESTE ES EL MEJOR., 12,)

#CLASES
#OBJETOS
#HERENCIA
#POLIMORFISMO