#ES"CRIBIR UN PROGRMA QUE ALMACENE LAS ASIGNACIONES DE UN CURSO
#(POR EJEMPLO MATEMATICA, FISICA, QUIMICA, HISTORIA Y LENGUAJE)
#EN UNA LISTA Y MUESTRE POR PANTALLA

asignaturas=["MATEMATICA", "FISICA", "QUIMICA", "HISTORIA","LENGUAJE"]
print(asignaturas)
